# .github/workflows/deploy.yml
name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Rust target for Pi
        run: |
          rustup target add armv7-unknown-linux-musleabihf

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: cross build --release --target armv7-unknown-linux-musleabihf

      - name: Upload to Pi
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: target/armv7-unknown-linux-musleabihf/release/fimbulfamb_api,Rocket.toml,words.txt
          target: ~/APIs/fimbulfamb_api

      - name: Restart service
        uses: appleboy/ssh-action@v1.2.5
        with:
            host: ${{ secrets.PI_HOST }}
            username: ${{ secrets.PI_USER }}
            key: ${{ secrets.PI_SSH_KEY }}
            port: 22
            script: sudo systemctl restart fimbulfamb_api